{% set name = "sasview" %}
{% set version = "5.0.3" %}
{% set sha256 = "f1ff482d29e80984dd4837cbb0c4fe8496f25567d9faa78f4f0fa52737ef10b9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SasView/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<36]
  entry_points:
    - sasview = sas.qtgui.MainWindow.MainWindow:run_sasview

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - bumps
    - h5py >=2.5
    - lxml
    - matplotlib-base
    - periodictable >=1.5.0
    - pillow
    - pyparsing >=2.0.0
    - pyqt >=5
    - qt5reactor
    - sasmodels
    - scipy
    - xhtml2pdf
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - sas.sasview
    - sas.qtgui
    - sas.qtgui.MainWindow
  commands:
    - which sasview  # [not win]
    - where sasview  # [win]

about:
  home: https://github.com/SasView/sasview
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: SasView is a Small Angle Scattering (SAS) analysis package
